#
datagrid:
    szkla-users-grid:
        source:
            type: orm
            query:
                select:
                    - u.id
                    - u.createTime
                    - u.modifyTime
                    - u.username
                    - u.email
                    - u.password
                    - u.note
                    - u.isActive
                from:
                    - { table: SzklaProductGridBundle:User, alias u }
        columns:
            id:
                label: ID
                frontend_type: integer
            email:
                label: "E-mail"
                frontend_type: string
            username:
                label: Username
                frontend_type: string
            isActive:
                label: "Active"
                frontend_type: boolean
            createTime:
                label: "Created on"
                frontend_type: datetime
            modifyTime:
                label: "Modified on"
                frontend_type: datetime
            password:
                label: "Password Hash"
                frontend_type: string
            note:
                label: "Note"
                frontend_type: string
        sorters:
            columns:
                id:
                    data_name: u.id
                email:
                    data_name: u.email
                username:
                    data_name: u.username
                isActive:
                    data_name: u.isActive
                createTime:
                    data_name: u.createTime
                modifyTime:
                    data_name: u.modifyTime
                note:
                    data_name: u.note
            default:
                id: ASC
        filters:
            columns:
                id:
                    type: number
                    data_name: u.id
                email:
                    type: string
                    data_name: u.email
                username:
                    type: string
                    data_name: u.username
                isActive:
                    type: boolean
                    data_name: u.isActive
                createTime:
                    type: datetime
                    data_name: u.createTime
                modifyTime:
                    type: datetime
                    data_name: u.modifyTime
                note:
                    type: string
                    data_name: u.note

    products-grid:
        source:
            acl_resource: szkla_products.product_view
            type: orm
            query:
                select:
                    - p.id
                    - p.createTime
                    - p.modifyTime
                    - p.sku
                    - p.isActive
                from:
                    - { table: SzklaProductGridBundle:Product, alias: p }
        columns:
            sku:
                label: SKU
                frontend_type: string
            isActive:
                label: "Active?"
                frontend_type: boolean
            createTime:
                label: Created
                frontend_type: datetime
            modifyTime:
                label: Modified
                frontend_type: datetime
        properties:
            id: ~
            update_link:
                type: url
                route: szkla_products.product_update
                params:
                    - id
            view_link:
                type: url
                route: szkla_products.product_view
                params:
                    - id
            delete_link:
                type: url
                route: szkla_products_api_delete_product
                params:
                    - id
        sorters:
            columns:
                sku:
                    data_name: p.sku
                isActive:
                    data_name: p.isActive
                createTime:
                    data_name: p.createTime
                modifyTime:
                    data_name: p.modifyTime
            default:
                sku: ASC
        filters:
            columns:
                sku:
                    type: string
                    data_name: p.sku
                isActive:
                    type: boolean
                    data_name: p.isActive
                createTime:
                    type: datetime
                    data_name: p.createTime
                modifyTime:
                    type: datetime
                    data_name: p.modifyTime
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  szkla_products.product_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  szkla_products.product_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  szkla_products.product_delete

    attributes-grid:
        source:
            acl_resource: szkla_attributes.attribute_view
            type: orm
            query:
                select:
                    - a.id
                    - a.attributeName
                    - a.attributeType
                from:
                    - { table: SzklaProductGridBundle:Attribute, alias: a }
        columns:
            attributeName:
                label: "Name"
                frontend_type: string
            attributeType:
                label: "Type"
                frontend_type: string
        properties:
            id: ~
            update_link:
                type: url
                route: szkla_attributes.attribute_update
                params:
                    - id
            view_link:
                type: url
                route: szkla_attributes.attribute_view
                params:
                    - id
            delete_link:
                type: url
                route: szkla_attributes_api_delete_attribute
                params:
                    - id
        sorters:
            columns:
                attributeName:
                    data_name: a.attributeName
                attributeType:
                    data_name: a.attributeType
            default:
                attributeName: ASC
        filters:
            columns:
                attributeName:
                    type: string
                    data_name: a.attributeName
                attributeType:
                    type: string
                    data_name: a.attributeType
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  szkla_attributes.attribute_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  szkla_attributes.attribute_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  szkla_attributes.attribute_delete
