#
datagrid:
    products-grid:
        source:
            acl_resource: szkla_products.product_view
            type: orm
            query:
                select:
                    - p.id
                    - p.createTime
                    - p.modifyTime
                    - p.sku
                    - p.isActive
                from:
                    - { table: SzklaProductGridBundle:Products, alias: p }
        columns:
            sku:
                label: SKU
                frontend_type: string
            isActive:
                label: "Active?"
                frontend_type: boolean
            createTime:
                label: Created
                frontend_type: datetime
            modifyTime:
                label: Modified
                frontend_type: datetime
        properties:
            id: ~
            update_link:
                type: url
                route: szkla_products.product_update
                params:
                    - id
            view_link:
                type: url
                route: szkla_products.product_view
                params:
                    - id
            delete_link:
                type: url
                route: szkla_products_api_delete_product
                params:
                    - id
        sorters:
            columns:
                sku:
                    data_name: p.sku
                isActive:
                    data_name: p.isActive
                createTime:
                    data_name: p.createTime
                modifyTime:
                    data_name: p.modifyTime
            default:
                sku: ASC
        filters:
            columns:
                sku:
                    type: string
                    data_name: p.sku
                isActive:
                    type: boolean
                    data_name: p.isActive
                createTime:
                    type: datetime
                    data_name: p.createTime
                modifyTime:
                    type: datetime
                    data_name: p.modifyTime
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  szkla_products.product_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  szkla_products.product_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  szkla_products.product_delete
