# src/Szkla/Bundle/ProductGridBundle/SzklaProductGridBundle/Resources/config/form.yml
parameters:
    szkla_products.product.form.type.class: Szkla\Bundle\ProductGridBundle\Form\Type\ProductType
    szkla_attributes.attribute.form.type.class: Szkla\Bundle\ProductGridBundle\Form\Type\AttributeType

services:
    szkla_products.form.type.product:
        class: %szkla_products.product.form.type.class%
        tags:
            - { name: form.type, alias: szkla_products }

    szkla_attributes.form.type.attribute:
        class: %szkla_attributes.attribute.form.type.class%
        tags:
            - { name: form.type, alias: szkla_attributes }
