# src/Szkla/Bundle/ProductGridBundle/Resources/config/oro/navigation.yml
oro_menu_config:
    items:
        skla_products_list:
            label: "Szkla Products"
            route: szkla_products.products_index
    tree:
        application_menu:
            children:
                skla_products_list: ~
