# src/Szkla/Bundle/ProductGridBundle/Resources/config/oro/navigation.yml
oro_menu_config:
    items:
        szkla_main:
            label: "Szkla.com"
            uri: "#"
        szkla_products_list:
            label: "Products"
            route: szkla_products.products_index
        szkla_attributes_list:
            label: "Attributes"
            route: szkla_attributes.attributes_index
        szkla_users_list:
            label: "Szkla.com Users"
            route: szkla_user.user_index
    tree:
        application_menu:
            children:
                szkla_main:
                    children:
                        szkla_products_list: ~
                        szkla_attributes_list: ~
                szkla_users_list: ~
