#
# XXX: Seems like this file should be placed in the directory above
#
#entity_config:
#    szkla:
#        entity:
#            products:
#                sku:
#                    options:
#                        default_value: "SZKL0000-0000-ABCD-XYZ"
#                        translatable:  false
#                        indexed:       true
#                        priority:      100
#                    grid:
#                        type:        string
#                        label:       SKU
#                        show_filter: true
#                        filterable:  true
#                        filter_type: string
#                        sortable:    true
#                    form:
#                        type: text
#                        options:
#                            block: entity
#                            label: SKU
#                isActive:
#                    options:
#                        translatable:  false
#                        indexed:       true
#                        priority:      90
#                    grid:
#                        type:        boolean
#                        label:       "Active?"
#                        show_filter: true
#                        filterable:  true
#                        filter_type: boolean
#                        sortable:    true
#                    form:
#                        type: choice
#                        options:
#                            block:       entity
#                            label:       'Active?'
#                            choices:     ['No', 'Yes']
#                            empty_value: false
#            attributes:
#                attributeName:
#                    options:
#                        default_value: "99_attribute_name"
#                        translatable:  false
#                        indexed:       true
#                        priority:      100
#                    grid:
#                        type:        string
#                        label:       "Name"
#                        show_filter: true
#                        filterable:  true
#                        filter_type: string
#                        sortable:    true
#                    form:
#                        type: text
#                        options:
#                            block: entity
#                            label: Name
#                attributeType:
#                    options:
#                        translatable:  false
#                        indexed:       true
#                        priority:      90
#                    grid:
#                        type:        string
#                        label:       "Type"
#                        show_filter: true
#                        filterable:  true
#                        filter_type: string
#                        sortable:    true
#                    form:
#                        type: choice
#                        options:
#                            block:       entity
#                            label:       'Type'
#                            choices:     ['integer', 'decimal', 'datetime', 'varchar', 'text']
#                            empty_value: false
